@local=http://localhost:3000/users
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODNiMjc3ZjdhMGY2NTBmOTZlZDE0MzYiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzQ4NzA3MjI3fQ.2zGWD3iBS-6hC3x9FYIWr4acDQu8Yu_plvp0kVklRrM

POST {{local}}
Content-Type: application/json

{
    "name": {
        "first": "lady",
        "last":"schneider"
    },
    "email":"morLady@mor.com",
    "password":"Lady123456!",
    "image":{},
    "address":{
        "country":"israel",
        "city":"tel-aviv",
        "street":"levitan",
        "houseNumber": 4
    },
    "age":35,
    "interests":["workout"],
    "isBusiness": true
}

###
POST {{local}}/login
Content-Type: application/json

{
    "email":"mor@mor.com",
    "password":"Smors123456!"
}

###
GET {{local}}


###
GET {{local}}/683b277f7a0f650f96ed1436
x-auth-token: {{token}}

###
PUT {{local}}/683b277f7a0f650f96ed1436
Content-Type: application/json
x-auth-token: {{token}}

{
    "name": {
        "first": "Kofiko",
        "last":"schneider"
    },
    "email":"mor@mor.com",
    "password":"Smors123456!",
    "image":{},
    "address":{
        "country":"israel",
        "city":"tel-aviv",
        "street":"levitan",
        "houseNumber": 4
    },
    "age":35,
    "interests":["workout"],
    "isBusiness": true
}

###
DELETE {{local}}/683b277f7a0f650f96ed1436
x-auth-token: {{token}}